beer_shop/beer_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from payment import webhooks


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path(_('cart/'), include('cart.urls', namespace='cart')),
    path(_('orders/'), include('orders.urls', namespace='orders')),
    path(_('payment/'), include('payment.urls', namespace='payment')),
    path(_('coupons/'), include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop')),
)

urlpatterns += [
    path('payment/webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beer_shop/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

beer_shop/shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', index_page, name='index_page'),
    path('products/', product_list, name='product_list'),
    path('<slug:category_slug>/products/', product_list, name='product_list_by_category'),
    path('products/<slug:country_slug>/', product_list, name='product_list_by_country'),
    path('<slug:category_slug>/products/<slug:country_slug>/',
         product_list,
         name='product_list_by_category_and_by_country'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
]

beer_shop/shop/models.py
from django.db import models
from django.urls import reverse
from parler.models import TranslatableModel, TranslatedFields


class Category(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=150),
        slug=models.SlugField(max_length=150, unique=True),
    )

    class Meta:
        # ordering = ['name']
        # indexes = [
        #     models.Index(fields=['name']),
        # ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', kwargs={'category_slug': self.slug})


class Country(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=150, unique=True),
        slug=models.SlugField(max_length=150, unique=True),
    )

    class Meta:
        # ordering = ['name']
        # indexes = [
        #     models.Index(fields=['name']),
        # ]
        verbose_name = 'country'
        verbose_name_plural = 'countries'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_country', kwargs={'country_slug': self.slug})


class Product(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=200),
        slug=models.SlugField(max_length=200),
        description=models.TextField(blank=True),
    )
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    country = models.ForeignKey(Country, related_name='products', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    strength = models.FloatField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        # ordering = ['name']
        indexes = [
            # models.Index(fields=['id', 'slug']),
            # models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.pk, self.slug])

beer_shop/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from cart.forms import CartAddProductForm
from .models import Product, Category, Country
from .recommender import Recommender


def product_list(request, category_slug=None, country_slug=None):
    category = None
    country = None
    categories = Category.objects.all()
    countries = Country.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug and country_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(Category,
                                     translations__language_code=language,
                                     translations__slug=category_slug)
        country = get_object_or_404(Country,
                                    translations__language_code=language,
                                    translations__slug=country_slug)
        products = products.filter(category=category).filter(country=country)
    elif category_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(Category,
                                     translations__language_code=language,
                                     translations__slug=category_slug)
        products = products.filter(category=category)
    elif country_slug:
        language = request.LANGUAGE_CODE
        country = get_object_or_404(Country,
                                    translations__language_code=language,
                                    translations__slug=country_slug)
        products = products.filter(country=country)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'country': country,
                   'categories': categories,
                   'countries': countries,
                   'products': products})

# class ProductListView(ListView):
#     model = Product
#     template_name = 'shop/product/list.html'
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super().get_context_data(**kwargs)
#         try:
#             context['category'] = Category.objects.get(slug=self.kwargs['category_slug'])
#         except:
#             context['category'] = None
#         context['categories'] = Category.objects.all()
#         try:
#             context['country'] = Country.objects.get(slug=self.kwargs['country_slug'])
#         except:
#             context['country'] = None
#         context['countries'] = Country.objects.all()
#         context['products'] = Product.objects.filter(available=True)
#         if context['category'] and context['country']:
#             context['products'] = Product.objects.filter(available=True) \
#                 .filter(category=context['category']) \
#                 .filter(country=context['country'])
#         elif context['category']:
#             context['products'] = Product.objects.filter(available=True) \
#                 .filter(category=context['category'])
#         elif context['country']:
#             context['products'] = Product.objects.filter(available=True) \
#                 .filter(country=context['country'])
#
#         return context


def product_detail(request, id, slug):
    # language = request.LANGUAGE_CODE
    product = get_object_or_404(Product,
                                id=id,
                                # translations__language_code=language,
                                # translations__slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form,
                   'recommended_products': recommended_products})


# class ProductDetailView(DetailView):
#     model = Product
#     template_name = 'shop/product/detail.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         r = Recommender()
#         context['cart_product_form'] = CartAddProductForm()
#         context['recommended_products'] = r.suggest_products_for([context['product']], 4)
#         return context


def index_page(request):
    return redirect('shop:product_list')

beer_shop/shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load i18n %}
{% load static %}

{% block title %}
{% endblock %}

{% block sidebar %}
{% endblock %}

{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="img-fluid rounded-start">
        <h1>{{ product.name }}</h1>
        <h2>
            <a href="{{ product.category.get_absolute_url }}" class="btn btn-primary">
            {{ product.category }}
            </a>
        </h2>
        <p class="price">${{ product.price }}</p>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input class="btn btn-success" type="submit" value="{% trans 'Add to cart' %}">
        </form>
        strength {{ product.strength }}%
        {{ product.description|linebreaks }}
        <a href="{{ product.country.get_absolute_url }}" class="country">
            Made in {{ product.country }}
        </a>

        {% if recommended_products %}
            <div class="recommendations">
                <h3>{% trans 'People who bought this also bought' %}</h3>
                {% for p in recommended_products %}
                    <div class="item">
                        <a href="{{ p.get_absolute_url }}">
                        <img src="{% if p.image %}{{ p.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"> </a>
                        <p><a href="{{ p.get_absolute_url }}">{{ p.name }}</a></p>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

beer_shop/shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load i18n %}
{% load static %}

{% block title %}
    {% if category and country %}
        {{ category.name }} {% trans 'beer from' %} {{ country.name }}
    {% elif category %}
        {{ category.name }} {% trans 'beer' %}
    {% elif country %}
        {% trans 'Beer from' %} {{ country.name }}
    {% else %}
        {% trans 'Products' %}
    {% endif %}
{% endblock %}

{% block content%}
<div id="sidebar">
    <h3>{% trans 'Categories' %}</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% if not country %}{% url 'shop:product_list' %}{% else %}{{ country.get_absolute_url }}{% endif %}">{% trans 'All' %}</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{% if not country %}{{ c.get_absolute_url }}{% else %}{% url 'shop:product_list_by_category_and_by_country' category_slug=c.slug country_slug=country.slug %}{% endif %}">
              {{ c.name }}
          </a>
        </li>
      {% endfor %}
    </ul>
    <h3>{% trans 'Country' %}</h3>
    <ul>
      <li {% if not country %}class="selected"{% endif %}>
        <a href="{% if not category %}{% url 'shop:product_list' %}{% else %}{{ category.get_absolute_url }}{% endif %}">{% trans 'All' %}</a>
      </li>
      {% for c in countries %}
        <li {% if country.slug == c.slug %}class="selected"{% endif %}>
          <a href="{% if not category %}{{ c.get_absolute_url }}{% else %}{% url 'shop:product_list_by_category_and_by_country' category_slug=category.slug country_slug=c.slug %}{% endif %}">
              {{ c.name }}
          </a>
        </li>
      {% endfor %}
    </ul>
</div>

<div id="main" class="product-list">
    <h1>
        {% if category and country %}
            {{ category.name }} {% trans 'beer from' %} {{ country.name }}
        {% elif category %}
            {{ category.name }} {% trans 'beer' %}
        {% elif country %}
            {% trans 'Beer from' %} {{ country.name }}
        {% else %}
            {% trans 'Products' %}
        {% endif %}
    </h1>

    <div class="row row-cols-1 row-cols-md-4 g-4">
        {% for product in products %}
            <div class="col">
                <div class="card text-bg-success mb-3 h-100">
                    <div class="card-body">
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" class="card-img-top">
                        </a>
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p>{{ product.category }}</p>
                        <p>{% trans 'Made in' %} {{ product.country }}</p>
                        <p class="card-text">${{ product.price }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}